### PR TITLE
Fix screenshot viewer does not fit screen width when image height is …

### LINKED ISSUE #674: [Smoke Test] Screenshots of some websites are wider than the device width
screenshot

Build: 855
DuT: Samsung, Advan

### PR DESCRIPTION
**Pull request by joseph-yar**
…smaller than screen height.

- Closes #674

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/screenshot/ScreenshotViewerActivity.java [hunk 1]
```diff
@@ -261,6 +261,8 @@ private void initScreenshotInfo(boolean withShare) {
             final ImageSource imageSource;
             mImageUri = Uri.fromFile(new File(mScreenshot.getImageUri()));
             imageSource = ImageSource.uri(mImageUri);
+            mImgScreenshot.setMinimumScaleType(SubsamplingScaleImageView.SCALE_TYPE_CUSTOM);
```
Comment (mTwTm) [inline app/src/main/java/org/mozilla/focus/screenshot/ScreenshotViewerActivity.java]: The other inits including a setMinimumScaleType is in
`onCreate`
Let's put these there?
