### PR TITLE
Bandage for intentOpenSettings when a detached Fragment is passed in

### LINKED ISSUE #1355: crash - java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.support.v4.app.FragmentActivity.getPackageName()' on a null object reference
--------- beginning of crash
01-25 13:48:17.925 16849 16849 E AndroidRuntime: FATAL EXCEPTION: main
01-25 13:48:17.925 16849 16849 E AndroidRuntime: Process: org.mozilla.rocket, PID: 16849
01-25 13:48:17.925 16849 16849 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.support.v4.app.FragmentActivity.getPackageName()' on a null object reference
01-25 13:48:17.925 16849 16849 E AndroidRuntime: 	at org.mozilla.focus.utils.IntentUtils.intentOpenSettings(IntentUtils.java:159)
01-25 13:48:17.925 16849 16849 E AndroidRuntime: 	at org.mozilla.focus.permission.PermissionHandler$5.onClick(PermissionHandler.java:182)
01-25 13:48:17.925 16849 16849 E AndroidRuntime: 	at android.support.design.widget.Snackbar$1.onClick(Snackbar.java:255)
01-25 13:48:17.925 16849 16849 E AndroidRuntime: 	at android.view.View.performClick(View.java:5280)
01-25 13:48:17.925 16849 16849 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:21239)
01-25 13:48:17.925 16849 16849 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
01-25 13:48:17.925 16849 16849 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-25 13:48:17.925 16849 16849 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:224)
01-25 13:48:17.925 16849 16849 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5526)
01-25 13:48:17.925 16849 16849 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-25 13:48:17.925 16849 16849 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-25 13:48:17.925 16849 16849 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-25 13:48:17.940   914  3803 D ActivityManager: New dropbox entry: org.mozilla.rocket, data_app_crash, 58d7d46a-844d-484c-9935-648fcaeb4f07
01-25 13:48:17.957   914  3803 W ActivityManager:   Force finishing activity org.mozilla.rocket/.activity.MainActivity
01-25 13:48:17.960   371  2966 D AudioFlinger: mixer(0xae800000) throttle end: throttle time(4)
01-25 13:48:18.022 12383 17185 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1271 android.content.ContextWrapper.bindService:604 com.sonyericsson.crashmonitor.MiscTaAdapter.open:90 com.sonyericsson.crashmonitor.service.CrashMonitorService.onInit:127 com.sonyericsson.crashmonitor.service.CrashMonitorService.onHandleIntent:192 
01-25 13:48:18.039   914 29533 I chatty  : uid=1000(system) RenderThread expire 1 line
01-25 13:48:18.472   914   946 W ActivityManager: Activity pause timeout for ActivityRecord{e36cb37 u0 org.mozilla.rocket/.activity.MainActivity t37 f}
01-25 13:48:18.589  3541  4263 D renderlib: nfd:0x9ee00000, bgfd:0x0
01-25 13:48:18.589  3722  3722 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@35b651c time:21360671
01-25 13:48:18.589  3541  4263 I renderlib: reset flag
01-25 13:48:18.618  3541  4263 D renderer: remove bg texture
01-25 13:48:18.618  3541  4263 D renderer: noise texture: 1080, 1920, 0x9ee00000
01-25 13:48:18.714   914   966 I chatty  : uid=1000(system) android.display expire 3 lines
01-25 13:48:20.984   371  2966 D audio_hw_primary: out_standby: enter: stream (0xb5b37380) usecase(1: low-latency-playback)
01-25 13:48:20.984   371  2966 D hardware_info: hw_info_append_hw_type : device_name = speaker
01-25 13:48:21.098   371  2966 W audio_hw_primary: disable_snd_device: device ref cnt is already 0
01-25 13:48:21.098   371  2966 D audio_hw_extn: audio_extn_get_anc_enabled: anc_enabled:0
01-25 13:48:23.233   914   933 D WifiService: acquireWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@9a2a178}
01-25 13:48:23.335   914  3138 D WifiService: releaseWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@9a2a178}
01-25 13:48:28.737   914   946 W ActivityManager: Activity destroy timeout for ActivityRecord{e36cb37 u0 org.mozilla.rocket/.activity.MainActivity t37 f}
01-25 13:48:29.119   393   393 I chatty  : uid=1000(system) illumination_se expire 121 lines
01-25 13:48:32.842   914   969 I PowerManagerService: Going to sleep due to screen timeout (uid 1000)...
01-25 13:48:32.845   914   969 I PowerManagerService: Sleeping (uid 1000)...
01-25 13:48:32.903   393   414 I chatty  : uid=1000(system) illumination_se expire 6 lines
01-25 13:48:32.903   399  1036 D fast-dormancy: [FDM]: Send status SCREEN_STATUS_OFF
01-25 13:48:32.903   399   399 D fast-dormancy: [FDM]: received fdmsg.type: 4, fdmsg.buf[0]: 2
01-25 13:48:32.906   491 17243 I chatty  : uid=1000(system) /system/bin/mm-pp-daemon expire 1 line
01-25 13:48:33.065   371  2985 D audio_hw_primary: adev_set_parameters: enter: screen_state=off
01-25 13:48:33.065   371  2985 D audio_hw_extn: audio_extn_set_anc_parameters: anc_enabled:0
01-25 13:48:33.065   371  2985 D audio_hw_extn: audio_extn_get_anc_enabled: anc_enabled:0
01-25 13:48:33.065   371  2985 E bt_a2dp_hw: adev_set_parameters: ERROR: set param called even when stream out is null
01-25 13:48:33.109  3586  5669 I chatty  : uid=1027(nfc) AsyncTask #5 expire 36 lines
01-25 13:48:33.169  3586  4494 I chatty  : uid=1027(nfc) AsyncTask #1 expire 197 lines
01-25 13:48:33.330  3586  4501 I chatty  : uid=1027(nfc) AsyncTask #1 expire 11 lines
01-25 13:48:34.054   914   966 I DisplayManagerService: Display device changed state: "Built-in Screen", OFF
01-25 13:48:34.263   914  2993 I chatty  : uid=1000(system) PhotonicModulat expire 4 lines
01-25 13:48:37.938  3021  3021 D PhoneStatusBar: disable: < expand ICONS* alerts SYSTEM_INFO* back home recent clock search quick_settings >
01-25 13:48:37.950  3021  3021 D ConnectivityManager: getMobileDataEnabled()+ subId=2
01-25 13:48:37.951  3665  3742 D PhoneInterfaceManager: [PhoneIntfMgr] getDataEnabled: subId=2 phoneId=0
01-25 13:48:37.951  3665  3742 D PhoneInterfaceManager: [PhoneIntfMgr] getDataEnabled: subId=2 retVal=true
01-25 13:48:37.951  3021  3021 D ConnectivityManager: getMobileDataEnabled()- subId=2 retVal=true
01-25 13:48:37.973  3021  4276 D ConnectivityManager: getMobileDataEnabled()+ subId=2
01-25 13:48:37.977  3665  4100 D PhoneInterfaceManager: [PhoneIntfMgr] getDataEnabled: subId=2 phoneId=0
01-25 13:48:37.977  3665  4100 D PhoneInterfaceManager: [PhoneIntfMgr] getDataEnabled: subId=2 retVal=true
01-25 13:48:50.287   466   502 V sysmon-usb_watt_limit: uevent_handler [349] LOCK 0xb6628078 from 502
01-25 13:48:50.288   466   502 V sysmon-usb_watt_limit: uevent_handler mutex 0xb6628078 GOT by 502
01-25 13:48:50.297  3021  4276 D ConnectivityManager: getMobileDataEnabled()- subId=2 retVal=true
01-25 13:48:50.307  3021  4276 D ConnectivityManager: getMobileDataEnabled()+ subId=2
01-25 13:48:50.308   466   502 V sysmon-usb_watt_limit: uevent_handler [383] UNLOCK 0xb6628078 from 502
01-25 13:48:50.308   466   502 V sysmon-dc_watt_limit: uevent_handler [349] LOCK 0xb6bf406c from 502
01-25 13:48:50.308   466   502 V sysmon-dc_watt_limit: uevent_handler mutex 0xb6bf406c GOT by 502
01-25 13:48:50.309  3665  3742 D PhoneInterfaceManager: [PhoneIntfMgr] getDataEnabled: subId=2 phoneId=0
01-25 13:48:50.309  3665  3742 D PhoneInterfaceManager: [PhoneIntfMgr] getDataEnabled: subId=2 retVal=true
01-25 13:48:50.310  3021  4276 D ConnectivityManager: getMobileDataEnabled()- subId=2 retVal=true
01-25 13:48:50.337   466   502 V sysmon-dc_watt_limit: uevent_handler [383] UNLOCK 0xb6bf406c from 502
01-25 13:48:50.347  3021  3021 D PhoneStatusBar: disable: < expand ICONS alerts SYSTEM_INFO back HOME* RECENT* clock SEARCH* quick_settings >
01-25 13:48:50.367  3665  3665 D TransmitPowerReceiver: Old PowerLevel: 6, current PowerLevel: 6
01-25 13:48:50.406  3665  3665 D TransmitPowerReceiver: Old PowerLevel: 6, current PowerLevel: 6
01-25 13:48:50.510   466   502 V sysmon-usb_watt_limit: uevent_handler [349] LOCK 0xb6628078 from 502
01-25 13:48:50.510   466   502 V sysmon-usb_watt_limit: uevent_handler mutex 0xb6628078 GOT by 502
01-25 13:48:50.539   466   502 V sysmon-usb_watt_limit: uevent_handler [383] UNLOCK 0xb6628078 from 502
01-25 13:48:50.572   466   502 V sysmon-dc_watt_limit: uevent_handler [349] LOCK 0xb6bf406c from 502
01-25 13:48:50.572   466   502 V sysmon-dc_watt_limit: uevent_handler mutex 0xb6bf406c GOT by 502
01-25 13:48:50.585   466   502 V sysmon-dc_watt_limit: uevent_handler [383] UNLOCK 0xb6bf406c from 502
01-25 13:48:50.619  3665  3665 D TransmitPowerReceiver: Old PowerLevel: 6, current PowerLevel: 6
01-25 13:48:50.630   466   502 V sysmon-usb_watt_limit: uevent_handler [349] LOCK 0xb6628078 from 502
01-25 13:48:50.630   466   502 V sysmon-usb_watt_limit: uevent_handler mutex 0xb6628078 GOT by 502
01-25 13:48:50.668   466   502 V sysmon-usb_watt_limit: uevent_handler [383] UNLOCK 0xb6628078 from 502
01-25 13:48:50.707   466   502 V sysmon-dc_watt_limit: uevent_handler [349] LOCK 0xb6bf406c from 502
01-25 13:48:50.707   466   502 V sysmon-dc_watt_limit: uevent_handler mutex 0xb6bf406c GOT by 502
01-25 13:48:50.730   466   502 V sysmon-dc_watt_limit: uevent_handler [383] UNLOCK 0xb6bf406c from 502
01-25 13:48:50.739   914   946 I ActivityManager: Start proc 17298:com.sonyericsson.capabilities/1000 for broadcast com.sonyericsson.capabilities/.DefCapUpdaterReceiver
01-25 13:48:50.794  3665  3665 D TransmitPowerReceiver: Old PowerLevel: 6, current PowerLevel: 6
01-25 13:48:50.872  3665  3665 D TransmitPowerReceiver: Old PowerLevel: 6, current PowerLevel: 6
01-25 13:48:50.889 17298 17298 I chatty  : uid=1000(system) com.sonyericsson.capabilities expire 5 lines
01-25 13:48:50.905   914  3055 I ActivityManager: Start proc 17320:com.sonymobile.enterprise.service/1000 for broadcast com.sonymobile.enterprise.service/.UsbReceiver
01-25 13:48:51.169 17320 17320 I chatty  : uid=1000(system) com.sonymobile.enterprise.service expire 5 lines
01-25 13:48:51.219 17320 17320 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1207 android.content.ContextWrapper.startService:581 android.content.ContextWrapper.startService:581 com.sonymobile.enterprise.service.UsbReceiver.onReceive:31 android.app.ActivityThread.handleReceiver:2782 
01-25 13:48:51.314   914  3647 I ActivityManager: Start proc 17346:com.sonymobile.mirrorlink.system/1000 for broadcast com.sonymobile.mirrorlink.system/com.sonymobile.mirrorlink.UsbStateReceiver
01-25 13:48:51.523   466   502 V sysmon-usb_watt_limit: uevent_handler [349] LOCK 0xb6628078 from 502
01-25 13:48:51.524   466   502 V sysmon-usb_watt_limit: uevent_handler mutex 0xb6628078 GOT by 502
01-25 13:48:51.532 17346 17346 I chatty  : uid=1000(system) com.sonymobile.mirrorlink.system expire 27 lines
01-25 13:48:51.547   466   502 V sysmon-usb_watt_limit: uevent_handler [383] UNLOCK 0xb6628078 from 502
01-25 13:48:51.591   466   502 V sysmon-dc_watt_limit: uevent_handler [349] LOCK 0xb6bf406c from 502
01-25 13:48:51.591   466   502 V sysmon-dc_watt_limit: uevent_handler mutex 0xb6bf406c GOT by 502
01-25 13:48:51.599   466   502 V sysmon-dc_watt_limit: uevent_handler [383] UNLOCK 0xb6bf406c from 502
01-25 13:48:51.608   914   969 I PowerManagerService: Waking up from sleep (uid 1000)...
01-25 13:48:51.617   914   914 I EntropyMixer: Writing entropy...
01-25 13:48:51.628   914   969 I DisplayPowerController: Blocking screen on until initial contents have been drawn.
01-25 13:48:51.629  3665  3665 D TransmitPowerReceiver: Old PowerLevel: 6, current PowerLevel: 6
01-25 13:48:51.674   914  2840 I ActivityManager: Start proc 17370:com.sonymobile.photoanalyzer/u0a98 for broadcast com.sonymobile.photoanalyzer/.service.PowerReceiver

Device: Sony Z3C
Rocket version: 1.0.3 (1902)
Android version: 6.0.1
WebView version: 63.0.3239.111

### PR DESCRIPTION
**Pull request by mTwTm**
Fixes #1355

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/utils/IntentUtils.java [hunk 1]
```diff
@@ -154,9 +154,13 @@ public static void intentOpenSettings(Activity activity, int requestCode) {
...
+        Activity host = fragment.getActivity();
+        if (host == null) {
+           return;
+        }
         Intent intent = new Intent();
         intent.setAction(android.provider.Settings.ACTION_APPLICATION_DETAILS_SETTINGS);
-        Uri uri = Uri.fromParts("package", fragment.getActivity().getPackageName(), null);
+        Uri uri = Uri.fromParts("package", host.getPackageName(), null);
         intent.setData(uri);
         fragment.startActivityForResult(intent, requestCode);
```
Comment (idiotmax) [inline app/src/main/java/org/mozilla/focus/utils/IntentUtils.java]: What if the activity is going to be finished, would it be safer if we use activity.startActivityForResult()?
Or, should we check isDestroyed or isFinishing?

Comment (mTwTm) [reply app/src/main/java/org/mozilla/focus/utils/IntentUtils.java]: activity.startActivityForResult() will not work. activity.onActivityResult will be triggered rather then fragment.onActivityResult and that will make permissionhandler hard to use since it will couple the host activity and the fragment.

On the other hand, yeah it never hurts to add some checks but I think that Snackbar 3 seconds is the most crucial part. Lifecycle is like 1/1000 of the reproduce rate.
