### PR TITLE
Monitor turbomode config during create/destroy lifecycle

### LINKED ISSUE #2838: Turbo mode not working via "Menu --> Settings -> Turbo mode switch"
**Steps To Reproduce**
1. Launch Firefox
2. Go to a site with ads
3. Menu -> settings 
4. Disable/enable turbo mode

**Actual behavior**
disable/enable turbo mode is not working. 

**Screenshots/videos**
https://drive.google.com/open?id=1D0aZS6JyGhvSoTBZ4d83N8l6GsUYg7yh

**Device info (please complete the following information):**

-  Device:nexus 5
- OS: Android: 6.0.1
- WebView: 69.0.3497.100
- Firefox Lite: 1.0.0(7855)

notes:
Both disable and enable are not working.

### PR DESCRIPTION
**Pull request by mxlius**
Closes #2838

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/activity/MainActivity.java [hunk 1]
```diff
@@ -777,14 +778,24 @@ public void onSharedPreferenceChanged(SharedPreferences sharedPreferences, Strin
             if (browserFragment != null) {
                 browserFragment.setContentBlockingEnabled(turboEnabled);
             }
-            menu.findViewById(R.id.menu_turbomode).setSelected(turboEnabled);
+            if (menu != null) {
```
Comment (mTwTm) [inline app/src/main/java/org/mozilla/focus/activity/MainActivity.java]: Consider making this complex operation a function that takes int id as parameter.

**Comment by mxlius** [comment]
Closes #2838
