### PR TITLE
Make sure when open from external App, the new tab will be at the end.

### LINKED ISSUE #2904: New tab is inserted at the top when open from external
**Steps To Reproduce**
1. Search in Firefox Lite or open external link in Firefox Lite

**Expected behavior**
2. A new tab should be inserted at the bottom of the tab list

**Actual behavior**
2. A new tab is inserted at the top of tab list

**Device info (please complete the following information):**
Reproduced on multiple devices.

**Reproduce rate**
Always

### PR DESCRIPTION
**Pull request by mTwTm**
Fixes #2904

### CODE REVIEW

File: components/feature/tabs/src/main/java/org/mozilla/rocket/tabs/SessionManager.kt [hunk 1]
```diff
@@ -75,39 +75,14 @@ class SessionManager @JvmOverloads constructor(
...
-
-        if (this.sessions.size > 0 && this.sessions.size == sessionList.size) {
-            focusRef = WeakReference<Session>(getTab(focusTabId))
-        }
-
-        notifyObservers { onSessionCountChanged(sessions.size) }
-    }
-
     fun restore(states: List<SessionWithState>, focusTabId: String?) {
+        // If Lite opened from external, 0 could be already occupied and should b the last item after restore.
```
Comment (cnevinc) [inline components/feature/tabs/src/main/java/org/mozilla/rocket/tabs/SessionManager.kt]: nit: s/b/be

Comment (mTwTm) [reply components/feature/tabs/src/main/java/org/mozilla/rocket/tabs/SessionManager.kt]: I can find where you mean by be but what's s and b?

Comment (mTwTm) [reply components/feature/tabs/src/main/java/org/mozilla/rocket/tabs/SessionManager.kt]: Ah it's should be, thanks!
