### PR TITLE
Make tab tray UI always be consistent with tab session

### LINKED ISSUE #1744: IndexOutOfBoundsException while close tab
on app version 3279

java.lang.IndexOutOfBoundsException: 
  at java.util.ArrayList.get (ArrayList.java:411)
  at org.mozilla.focus.tabs.tabtray.TabsSessionModel.removeTab (TabsSessionModel.java:50)
  at org.mozilla.focus.tabs.tabtray.TabTrayPresenter.tabCloseClicked (TabTrayPresenter.java:44)
  at org.mozilla.focus.tabs.tabtray.TabTrayFragment.onTabCloseClick (TabTrayFragment.java:205)
  at org.mozilla.focus.tabs.tabtray.TabTrayAdapter$InternalTabClickListener.dispatchOnClick (TabTrayAdapter.java:240)
  at org.mozilla.focus.tabs.tabtray.TabTrayAdapter$InternalTabClickListener.onClick (TabTrayAdapter.java:229)
  at android.view.View.performClick (View.java:5637)
  at android.view.View$PerformClick.run (View.java:22433)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6186)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:889)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:779)

### PR DESCRIPTION
**Pull request by pharspher**
Closes #1744

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/tabs/tabtray/TabsSessionModel.java [hunk 1]
```diff
@@ -5,48 +5,185 @@
...
+        } else {
+            if (BuildConfig.DEBUG) {
+                throw new ArrayIndexOutOfBoundsException("index: " + tabPosition + ", size: " + tabs.size());
+            }
+        }
+    }
+
+    @Override
+    public void subscribe(final Observer observer) {
+        if (onTabModelChangedListener == null) {
```
Comment (idiotmax) [inline app/src/main/java/org/mozilla/focus/tabs/tabtray/TabsSessionModel.java]: Is the listener can be ```subscribe``` once only? Because there's no set as null in ```unsubscribe```, the second pair of ```subscribe``` will not replace the ```observer``` reference in ```onTabModelChangeListener```

Comment (pharspher) [reply app/src/main/java/org/mozilla/focus/tabs/tabtray/TabsSessionModel.java]: Fixed, thanks!
