### PR TITLE
Fix the links of License page cannot be opened.

### LINKED ISSUE #1899: Nothing happens after tapping Menu -> Settings -> About -> Learn More -> Share on Twitter
STR:
 1. Launch Rocket 
 2. Tap Menu -> Settings -> About -> Learn More
 3. Scroll down and Tap "Share on Twitter" 

Expected result:
 - A user can share it on Twitter

Actual result: 
 - Nothing happens
 - Video: https://drive.google.com/open?id=1_l0Mz8USJtkY5Bb8q7vuP5IfBuLXJO8R 

Reproduced rate: 5/5

Device: Pixel 2
Rocket: 2.0.0(4045).night and 2.0.0(3585)
Android version: 8.1.0 
WebView version 67.0.3396.29

### LINKED ISSUE #1930: Can't open the links in License page
screenshot_20180516-154055

Can't open the Zelda and telemetry item. BTW the contents needs an update cause both projects have moved.

### PR DESCRIPTION
**Pull request by benjamin-cheng**
Close #1930, close #1899

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/fragment/InfoFragment.java [hunk 1]
```diff
@@ -43,13 +42,13 @@ public static InfoFragment create(String url) {
...
-        webViewSlot = (ViewGroup) view.findViewById(R.id.webview_slot);
-        webView = ((TabView) WebViewProvider.create(getContext(), null)).getView();
+        progressView = view.findViewById(R.id.progress);
+        ViewGroup webViewSlot = view.findViewById(R.id.webview_slot);
+        webView = (WebView) WebViewProvider.createDefaultWebView(getContext(), null);
         webViewSlot.addView(webView);
 
         final String url = getInitialUrl();
-        if (!(url.startsWith("http://") || url.startsWith("https://"))) {
+        if (url != null && !(url.startsWith("http://") || url.startsWith("https://"))) {
```
Comment (walkingice) [inline app/src/main/java/org/mozilla/focus/fragment/InfoFragment.java]: probably we can use `TextUtils.isEmpty(url)` here

File: app/src/main/java/org/mozilla/focus/fragment/DefaultWebFragment.java [hunk 2]
```diff
@@ -60,22 +57,20 @@
...
         final View view = inflateLayout(inflater, container, savedInstanceState);
 
-        webViewSlot = (ViewGroup) view.findViewById(R.id.webview_slot);
-        tabView = (TabView) WebViewProvider.create(getContext(), null);
-
-        webViewSlot.addView(tabView.getView());
         isWebViewAvailable = true;
-        tabView.setViewClient(createTabViewClient());
-        tabView.setChromeClient(createTabChromeClient());
+        DefaultWebViewClient webViewClient = (DefaultWebViewClient) createWebViewClient();
```
Comment (walkingice) [inline app/src/main/java/org/mozilla/focus/fragment/DefaultWebFragment.java]: is this type casting necessary?
