### PR TITLE
Catch IndexOutOfBounds exception thrown when querying for search-suggestion.

### LINKED ISSUE #1851: java.lang.ArrayIndexOutOfBoundsException in org.mozilla.focus.urlinput.UrlInputPresenter$HttpRequest.get
New on 3585

Ref: https://play.google.com/apps/publish/?account=7083182635971239206#AndroidMetricsErrorsPlace:p=org.mozilla.rocket&appid=4975490230001076778&appVersion=CANARY&clusterName=apps/org.mozilla.rocket/clusters/199cfeec&detailsSpan=7

java.lang.RuntimeException: 
 
  at android.os.AsyncTask$3.done (AsyncTask.java:330)
 
  at java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:354)
 
  at java.util.concurrent.FutureTask.setException (FutureTask.java:223)
 
  at java.util.concurrent.FutureTask.run (FutureTask.java:242)
 
  at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:255)
 
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
 
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
 
  at java.lang.Thread.run (Thread.java:776)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 
 
  at com.android.okhttp.okio.Buffer.writeByte (Buffer.java:973)
 
  at com.android.okhttp.internal.Platform.concatLengthPrefixed (Platform.java:130)
 
  at com.android.okhttp.internal.Platform.configureTlsExtensions (Platform.java:84)
 
  at com.android.okhttp.Connection.connectTls (Connection.java:230)
 
  at com.android.okhttp.Connection.connectSocket (Connection.java:199)
 
  at com.android.okhttp.Connection.connect (Connection.java:172)
 
  at com.android.okhttp.Connection.connectAndSetOwner (Connection.java:367)
 
  at com.android.okhttp.OkHttpClient$1.connectAndSetOwner (OkHttpClient.java:130)
 
  at com.android.okhttp.internal.http.HttpEngine.connect (HttpEngine.java:329)
 
  at com.android.okhttp.internal.http.HttpEngine.sendRequest (HttpEngine.java:246)
 
  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute (HttpURLConnectionImpl.java:457)
 
  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse (HttpURLConnectionImpl.java:405)
 
  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream (HttpURLConnectionImpl.java:243)
 
  at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream (DelegatingHttpsURLConnection.java:210)
 
  at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream (HttpsURLConnectionImpl.java)
 
  at org.mozilla.focus.urlinput.UrlInputPresenter$HttpRequest.get (UrlInputPresenter.java:123)
 
  at org.mozilla.focus.urlinput.UrlInputPresenter$QueryTask.doInBackground (UrlInputPresenter.java:98)
 
  at org.mozilla.focus.urlinput.UrlInputPresenter$QueryTask.doInBackground (UrlInputPresenter.java:86)
 
  at android.os.AsyncTask$2.call (AsyncTask.java:316)
 
  at java.util.concurrent.FutureTask.run (FutureTask.java:237)

### PR DESCRIPTION
**Pull request by pharspher**
Fix #1851

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/urlinput/UrlInputPresenter.java [hunk 1]
```diff
@@ -167,5 +156,34 @@ protected void onPostExecute(List<CharSequence> strings) {
...
+                InputStreamReader reader = new InputStreamReader(new BufferedInputStream(inputStream),
+                        "utf-8");
+                bufferedReader = new BufferedReader(reader);
+
+                String line;
+                while ((line = bufferedReader.readLine()) != null) {
+                    total.append(line).append('\n');
+                }
+            } finally {
+                IOUtils.closeQuietly(bufferedReader);
```
Comment (mTwTm) [inline app/src/main/java/org/mozilla/focus/urlinput/UrlInputPresenter.java]: Consider rework this part we Autoclosabe: https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html
