### PR TITLE
bug: to catch Exception in volume checking

### LINKED ISSUE #1088: java.lang.IllegalArgumentException
java.lang.IllegalArgumentException: 
 
  at android.os.Environment.isExternalStorageRemovable (Environment.java:1016)
 
  at org.mozilla.focus.utils.StorageUtils.getFirstRemovableMedia (StorageUtils.java:94)
 
  at org.mozilla.focus.utils.StorageUtils.getAppMediaDirOnRemovableStorage (StorageUtils.java:34)
 
  at org.mozilla.focus.utils.StorageUtils.getTargetDirOnRemovableStorageForDownloads (StorageUtils.java:62)
 
  at org.mozilla.focus.activity.MainActivity.asyncCheckStorage (MainActivity.java:775)
 
  at org.mozilla.focus.activity.MainActivity.access$300 (MainActivity.java:68)
 
  at org.mozilla.focus.activity.MainActivity$2.run (MainActivity.java:764)
 
  at java.lang.Thread.run (Thread.java:818)

### PR DESCRIPTION
**Pull request by walkingice**
to add try-catch in case of any unexpected situation which crash app.

to fix #1088

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/utils/StorageUtils.java [hunk 1]
```diff
@@ -91,8 +91,17 @@ static File getFirstRemovableMedia(@NonNull Context ctx) {
         final File[] files = ctx.getExternalMediaDirs();
         for (final File file : files) {
             // on some devices such as Oppo, it might return null
-            if ((file != null) && Environment.isExternalStorageRemovable(file)) {
-                return file;
+            if ((file != null)) {
+                // Environment will invoke internal API to check volume,
+                // and throws an IllegalArgumentException if the target path has any problem
+                try {
+                    if (Environment.isExternalStorageRemovable(file)) {
```
Comment (mTwTm) [inline app/src/main/java/org/mozilla/focus/utils/StorageUtils.java]: https://developer.android.com/reference/android/os/Environment.html#isExternalStorageRemovable() states it throws IllegalArgumentException if the path is not a valid storage device.

Let's not catch everything but just IllegalArgumentException since some thing/api may have changed and we want to know when it is broken.

File: app/src/main/java/org/mozilla/focus/utils/StorageUtils.java [hunk 2]
```diff
@@ -91,8 +91,17 @@ static File getFirstRemovableMedia(@NonNull Context ctx) {
         final File[] files = ctx.getExternalMediaDirs();
         for (final File file : files) {
             // on some devices such as Oppo, it might return null
-            if ((file != null) && Environment.isExternalStorageRemovable(file)) {
-                return file;
+            if ((file != null)) {
```
Comment (mTwTm) [inline app/src/main/java/org/mozilla/focus/utils/StorageUtils.java]: Would it be simpler to just do:

try {
   if ((file != null) && Environment.isExternalStorageRemovable(file)) {
   }
}

**Comment by walkingice** [comment]
updated to follow @mTwTm 's suggestion
