### PR TITLE
[Menu] Disable forward/reload/share/shortcut button if browser fragme…

### LINKED ISSUE #1589: Rocket crashes when trying to reload the home panel after closing all tabs
1. Close all tabs in tab view
2. Now at home panel with zero tabs
3. Tap menu and tap reload or X
4. Rocket crashes

### PR DESCRIPTION
**Pull request by pharspher**
…nt is not in the foreground, fix #1589

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/activity/MainActivity.java [hunk 1]
```diff
@@ -378,11 +378,7 @@ private void setUpMenu() {
     @VisibleForTesting
     public BrowserFragment getVisibleBrowserFragment() {
```
Comment (mTwTm) [inline app/src/main/java/org/mozilla/focus/activity/MainActivity.java]: Seems like some functions that depends on getVisibleBrowserFragment() will change behavior: for instance, when TopFragment is HomeFragment and TurboMode is switched, Site currently focused will not be reloaded. (However this sounds acceptable, lol.)

File: app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java [hunk 2]
```diff
@@ -575,6 +575,12 @@ public void onDestroyView() {
         super.onDestroyView();
     }
 
+    public void setImageBlockingEnabled(boolean enabled) {
+        for (Tab tab : tabsSession.getTabs()) {
+            tab.setImageBlockingEnabled(enabled);
+        }
+    }
+
```
Comment (walkingice) [inline app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java]: it would be sweet if we add `TODO: this implementation should not belong to Fragment` to this method, as well as `setContentBlockingEnabled`

File: app/src/webkit/java/org/mozilla/focus/webkit/WebkitView.java [hunk 3]
```diff
@@ -137,14 +134,37 @@ public void saveViewState(Bundle outState) {
...
 
     public boolean isBlockingEnabled() {
         return client.isBlockingEnabled();
     }
 
+    @Override
+    public void setImageBlockingEnabled(boolean enabled) {
+        WebSettings settings = getSettings();
+        if (enabled == settings.getBlockNetworkImage() &&
+                enabled == !settings.getLoadsImagesAutomatically()) {
```
Comment (walkingice) [inline app/src/webkit/java/org/mozilla/focus/webkit/WebkitView.java]: please move `&&` to the start of next line. Maybe to use `flag` is better than `enabled`? (since enabled indicate a happened-state of WebSettings)

File: app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java (hunk 2 above)
Comment (pharspher) [reply app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java]: comment added

File: app/src/webkit/java/org/mozilla/focus/webkit/WebkitView.java (hunk 3 above)
Comment (pharspher) [reply app/src/webkit/java/org/mozilla/focus/webkit/WebkitView.java]: already moved the operator to the head of the second line.
