### PR TITLE
Fix default browser telemetry, closes #1141

### LINKED ISSUE #1141: fix set default browser telemetry

### PR DESCRIPTION
**Pull request by idiotmax**

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/widget/DefaultBrowserPreference.java [hunk 1]
```diff
@@ -50,7 +50,12 @@ protected void onBindView(View view) {
     public void update() {
         if (switchView != null) {
             final Browsers browsers = new Browsers(getContext(), "http://www.mozilla.org");
-            switchView.setChecked(browsers.isDefaultBrowser(getContext()));
+            final boolean isDefaultBrowser = browsers.isDefaultBrowser(getContext());
+            switchView.setChecked(isDefaultBrowser);
+            Set<String> keySet = getSharedPreferences().getAll().keySet();
+            if(keySet.contains(getContext().getResources().getString(R.string.pref_key_default_browser)) || isDefaultBrowser) {
+                getEditor().putBoolean(getKey(), isDefaultBrowser).commit();
```
Comment (mTwTm) [inline app/src/main/java/org/mozilla/focus/widget/DefaultBrowserPreference.java]: apply() should be enough in this case.

File: app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.java [hunk 2]
```diff
@@ -196,6 +202,17 @@ public static void init(Context context) {
         }
     }
 
+    private static void updateDefaultBrowserStatus(Context context) {
+        final Browsers browsers = new Browsers(context, "http://www.mozilla.org");
+        final boolean isDefaultBrowser = browsers.isDefaultBrowser(context);
+        final SharedPreferences sharedPreferences = PreferenceManager.getDefaultSharedPreferences(context);
+        final Set<String> keySet = sharedPreferences.getAll().keySet();
+        final String prefDefaultBrowser = context.getResources().getString(R.string.pref_key_default_browser);
+        if (keySet.contains(prefDefaultBrowser) || isDefaultBrowser) {
```
Comment (mTwTm) [inline app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.java]: Let's have a Util in Settings.java
```
updatePrefDefaultBrowserIfNeeded(boolean isDefaultBrowser) {
    currentPrefDefault = ...
    if (currentPrefDefault != null) {
    }
    sharedPreferences.edit().putBoolean(prefDefaultBrowser, isDefaultBrowser).apply();
}
```
to make sure the logic is always applied

File: app/src/main/java/org/mozilla/focus/widget/DefaultBrowserPreference.java (hunk 1 above)
Comment (mTwTm) [reply app/src/main/java/org/mozilla/focus/widget/DefaultBrowserPreference.java]: Nevermind let's just use the earlier mentioned Util.
