### PR TITLE
Make Remote Config default value locale aware closes #2828

### LINKED ISSUE #2828: Rating card's dialog language doesn't tanslated
**Steps To Reproduce**
1. change language to indonesia
2. disable send data
3. relaunch app 5 times

**Expected behavior**
Rating card dialog should change language to indonesia.
**Actual behavior**
A clear and concise description of what you actually discovered.

**Screenshots/videos**
https://drive.google.com/open?id=12yVbulsqn1gCeqwJ4glNUwsyojjBoUVn

**Device info (please complete the following information):**

- Device:nexus 5
- OS: Android: 6.0.1
- WebView: 69.0.3497.100
- Firefox Lite: 1.0.0(7855)

### PR DESCRIPTION
**Pull request by cnevinc**
Whenever we change the app language, we clear the default value and request from the translated string resource again.

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/utils/FirebaseHelper.java [hunk 1]
```diff
@@ -236,6 +237,13 @@ protected void onPostExecute(Void result) {
         return remoteConfigDefault;
     }
 
+    @Override
+    void refreshRemoteConfigDefault(Context context) {
+        remoteConfigDefault = null;
+        getRemoteConfigDefault(context);
```
Comment (mTwTm) [inline app/src/main/java/org/mozilla/focus/utils/FirebaseHelper.java]: Maybe we don't need this line getRemoteConfigDefault(context);
It's quite unlikely but if during this getRemoteConfigDefault() another getRemoteConfigDefault() comes in things become nasty.
If you agree, I might also rename this function to clearRemoteConfigDefault
