### PR TITLE
Closes #2025: Be less strict to FirebaseEvent format error

### LINKED ISSUE #2022: Crashed: java.lang.IllegalArgumentException: change__setting__pref_did_show_rate_app_dialog exceeds Firebase event name length limit 46 of 40
STR: 
1. Uninstall Rocket
2. Install Rocket
3. Launch Rocket
4. Go Menu -> Settings 
5. Tap Give feedback
6. Tap X

Expected:
 - No crash

Actual:
 - Crashed 
 - This issue cannot be reproduced in Rocket2.1.1(4587)
 - Video: https://drive.google.com/open?id=1-FoUHvqAoVQrA01yQOJk3fzHXiHFtVow

Reproduce rate: 100%
 
Device: Pixel2
Android: 8.1.0
Rocket 2.1.1(4639)
WebView: 67.0.3396.49

--------- beginning of crash
05-29 16:39:28.595  8028  8028 E AndroidRuntime: FATAL EXCEPTION: main
05-29 16:39:28.595  8028  8028 E AndroidRuntime: Process: gro.allizom.zelda.beta, PID: 8028
05-29 16:39:28.595  8028  8028 E AndroidRuntime: java.lang.IllegalArgumentException: change__setting__pref_did_show_rate_app_dialog exceeds Firebase event name length limit 46 of 40
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at org.mozilla.focus.telemetry.FirebaseEvent.<init>(FirebaseEvent.java:50)
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at org.mozilla.focus.telemetry.FirebaseEvent.create(FirebaseEvent.java:56)
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at org.mozilla.focus.telemetry.TelemetryWrapper$EventBuilder.<init>(TelemetryWrapper.java:715)
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at org.mozilla.focus.telemetry.TelemetryWrapper.settingsEvent(TelemetryWrapper.java:288)
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at org.mozilla.focus.settings.SettingsFragment.onSharedPreferenceChanged(SettingsFragment.java:143)
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:561)
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:444)
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at org.mozilla.focus.utils.Settings.setRateAppDialogDidShow(Settings.java:129)
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at org.mozilla.focus.utils.DialogUtils.showRateAppDialog(DialogUtils.java:101)
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at org.mozilla.focus.settings.SettingsFragment.onPreferenceTreeClick(SettingsFragment.java:53)
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at android.preference.Preference.performClick(Preference.java:1146)
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:249)
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1158)
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3127)
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at android.widget.AbsListView$3.run(AbsListView.java:4042)
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
05-29 16:39:28.595  8028  8028 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
05-29 16:39:28.600  1109  2332 W ActivityManager:   Force finishing activity gro.allizom.zelda.beta/org.mozilla.focus.activity.SettingsActivity
05-29 16:39:28.610  1109  1156 I ActivityManager: Showing crash dialog for package gro.allizom.zelda.beta u0
05-29 16:39:28.653  1109  7786 I Adreno  : QUALCOMM build                   : 594927b, I916dfac403
05-29 16:39:28.653  1109  7786 I Adreno  : Build Date                       : 10/11/17
05-29 16:39:28.653  1109  7786 I Adreno  : OpenGL ES Shader Compiler Version: EV031.21.02.00
05-29 16:39:28.653  1109  7786 I Adreno  : Local Branch                     : mybranch28618966
05-29 16:39:28.653  1109  7786 I Adreno  : Remote Branch                    : quic/gfx-adreno.lnx.6.4.9-rel
05-29 16:39:28.653  1109  7786 I Adreno  : Remote Branch                    : NONE
05-29 16:39:28.653  1109  7786 I Adreno  : Reconstruct Branch               : NOTHING
05-29 16:39:28.660  1109  7786 I Adreno  : PFP: 0x005ff087, ME: 0x005ff063
05-29 16:39:28.665  1109  7786 I zygote64: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 1
05-29 16:39:28.667  1109  7786 I OpenGLRenderer: Initialized EGL, version 1.4
05-29 16:39:28.667  1109  7786 D OpenGLRenderer: Swap behavior 2
05-29 16:39:28.697  1109  1120 I zygote64: Background concurrent copying GC freed 46455(2MB) AllocSpace objects, 25(1268KB) LOS objects, 42% free, 17MB/30MB, paused 92us total 112.607ms
05-29 16:39:28.719  8028  8039 D         : TrackPlayerBase::~TrackPlayerBase()
05-29 16:39:28.719  8028  8039 D         : PlayerBase::~PlayerBase()
05-29 16:39:29.103  1109  1155 W ActivityManager: Activity pause timeout for ActivityRecord{3bb0209 u0 gro.allizom.zelda.beta/org.mozilla.focus.activity.SettingsActivity t1607 f}
05-29 16:39:31.714   725  1125 D audio_hw_primary: disable_audio_route: usecase(1) reset and update mixer path: low-latency-playback speaker
05-29 16:39:31.718   725  1125 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)
05-29 16:39:38.606  1109  1155 W ActivityManager: Launch timeout has expired, giving up wake lock!
05-29 16:39:44.302  1109  2332 I ActivityManager: START u0 {act=android.intent.action.APP_ERROR flg=0x10000000 cmp=com.android.vending/com.google.android.finsky.activities.AppCrashProxy (has extras)} from uid 1000
05-29 16:39:44.303   725  2109 D audio_hw_primary: enable_snd_device: snd_device(2: speaker)
05-29 16:39:44.303   725  2109 D audio_route: Apply path: speaker
05-29 16:39:44.305   725  2109 D ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 15, path = 0, app id = 0x11130, sample rate = 48000
05-29 16:39:44.305   725  2109 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE, vol index 0
05-29 16:39:44.305   725  2109 D ACDB-LOADER: ACDB -> GET_AFE_TOPOLOGY_ID for adcd_id 15, Topology Id 112fc
05-29 16:39:44.305   725  2109 D         : Failed to fetch the lookup information of the device 0000000F 
05-29 16:39:44.305   725  2109 D ACDB-LOADER: Error: ACDB AFE returned = -19
05-29 16:39:44.305   725  2109 D audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback speaker
05-29 16:39:44.305   725  2109 D audio_route: Apply path: low-latency-playback speaker
05-29 16:39:44.306  2093  2097 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 0]
05-29 16:39:44.307   742   742 D QCOM PowerHAL: LAUNCH HINT: ON
05-29 16:39:44.308   742   742 D QCOM PowerHAL: Activity launch hint handled
05-29 16:39:44.327  8028  8028 I Process : Sending signal. PID: 8028 SIG: 9
05-29 16:39:44.336   725  2109 D audio_hw_primary: out_write: retry previous failed cal level set
05-29 16:39:44.350  1109  1284 W InputDispatcher: channel '1a53f01 gro.allizom.zelda.beta/org.mozilla.focus.activity.SettingsActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
05-29 16:39:44.350  1109  1284 E InputDispatcher: channel '1a53f01 gro.allizom.zelda.beta/org.mozilla.focus.activity.SettingsActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
05-29 16:39:44.350  1109  1284 W InputDispatcher: channel 'b71264b gro.allizom.zelda.beta/org.mozilla.focus.activity.SettingsActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
05-29 16:39:44.350  1109  1284 E InputDispatcher: channel 'b71264b gro.allizom.zelda.beta/org.mozilla.focus.activity.SettingsActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
05-29 16:39:44.353  1109  1284 W InputDispatcher: channel '1493fea gro.allizom.zelda.beta/org.mozilla.rocket.activity.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
05-29 16:39:44.353  1109  1284 E InputDispatcher: channel '1493fea gro.allizom.zelda.beta/org.mozilla.rocket.activity.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
05-29 16:39:44.354  1109  1135 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=63, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ], android.os.BinderProxy@68ce6bf)
05-29 16:39:44.354  1109  2331 I WindowManager: WIN DEATH: Window{1a53f01 u0 gro.allizom.zelda.beta/org.mozilla.focus.activity.SettingsActivity}
05-29 16:39:44.354  1109  2331 W InputDispatcher: Attempted to unregister already unregistered input channel '1a53f01 gro.allizom.zelda.beta/org.mozilla.focus.activity.SettingsActivity (server)'
05-29 16:39:44.354  1109  2332 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=50, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ], android.os.BinderProxy@f06a18c)
05-29 16:39:44.355  1109  1685 I ActivityManager: Process gro.allizom.zelda.beta (pid 8028) has died: fore TOP 
05-29 16:39:44.355  1109  1157 W zygote64: kill(-8028, 9) failed: No such process
05-29 16:39:44.355  1109  1157 I zygote64: Successfully killed process cgroup uid 10231 pid 8028 in 0ms
05-29 16:39:44.356  1109  1443 I WindowManager: WIN DEATH: Window{1493fea u0 gro.allizom.zelda.beta/org.mozilla.rocket.activity.MainActivity}
05-29 16:39:44.356  1109  1443 W InputDispatcher: Attempted to unregister already unregistered input channel '1493fea gro.allizom.zelda.beta/org.mozilla.rocket.activity.MainActivity (server)'
05-29 16:39:44.357  1109  2332 I WindowManager: WIN DEATH: Window{b71264b u0 gro.allizom.zelda.beta/org.mozilla.focus.activity.SettingsActivity}
05-29 16:39:44.357  1109  2332 W InputDispatcher: Attempted to unregister already unregistered input channel 'b71264b gro.allizom.zelda.beta/org.mozilla.focus.activity.SettingsActivity (server)'
05-29 16:39:44.364  1109  1685 I ActivityManager: Killing 8081:com.chrome.beta:sandboxed_process0/u0a231i0 (adj 0): isolated not needed
05-29 16:39:44.364  1109  1157 W zygote64: Failed to open process cgroup uid 99000 pid 8081: No such file or directory
05-29 16:39:44.364  1109  1157 E zygote64: Error encountered killing process cgroup uid 99000 pid 8081: No such file or directory
05-29 16:39:44.367  1109  1164 W ActivityManager: setHasOverlayUi called on unknown pid: 8028
05-29 16:39:44.374  7247  7247 I AppLifecycleTracker: onActivityCreated: 
05-29 16:39:44.375  7247  7247 I Finsky  : [2] com.google.android.finsky.activities.AppCrashProxy.onCreate(108): Sending feedback for crashed gro.allizom.zelda.beta to com.google.android.gms

### LINKED ISSUE #2025: Fatal Exception: java.lang.IllegalArgumentException change__setting__pref_did_show_rate_app_dialog exceeds Firebase event name length limit 46 of 40

### PR DESCRIPTION
**Pull request by cnevinc**
1. Send Firebase events alone with Telemetry events
2. Add tests to make sure all FirebaseEvents are valid

Closes #2022

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/telemetry/FirebaseEvent.java [hunk 1]
```diff
@@ -44,10 +46,14 @@ private FirebaseEvent(@NonNull String category, @NonNull String method, @Nullabl
...
         // Android Studio also said we don't need to use a String builder here.
         this.eventName = method + EVENT_NAME_SEPARATOR + object + EVENT_NAME_SEPARATOR + value;
-        if (!AppConstants.isReleaseBuild() && this.eventName.length() > MAX_LENGTH_EVENT_NAME) {
+        if (this.eventName.length() > MAX_LENGTH_EVENT_NAME) {
             // TODO: check eventName should start with[a-zA-Z] , contains only [a-zA-A0-9_], and shouldn't
             // TODO: start with ^(?!(firebase_|google_|ga_)).*
-            throw new IllegalArgumentException(this.eventName + " exceeds Firebase event name length limit " + this.eventName.length() + " of " + MAX_LENGTH_EVENT_NAME);
+            logError("Event[" + this.eventName + "] exceeds Firebase event name length limit " + this.eventName.length() + " of " + MAX_LENGTH_EVENT_NAME);
+            // I want to keep the value part cause it's more important.
+            int lastPos = this.eventName.length();
```
[the remark this answers is not in the document]
Comment (cnevinc) [reply app/src/main/java/org/mozilla/focus/telemetry/FirebaseEvent.java]: I'll just rename the value part. Since cha and set is also misleading and can still make the name to long.

[the remark this answers is not in the document]
Comment (cnevinc) [reply app/src/main/java/org/mozilla/focus/telemetry/FirebaseEvent.java]: What's the part in telemetry that's not working?  I thought we also check the format before I we send it

File: app/src/main/java/org/mozilla/focus/telemetry/FirebaseEvent.java [hunk 2]
```diff
@@ -34,6 +39,8 @@
     static final int MAX_PARAM_SIZE = 25;
     static final int MAX_LENGTH_PARAM_NAME = 40;
     static final int MAX_LENGTH_PARAM_VALUE = 100;
+    private static final String TAG = "FirebaseEvent";
+    private static ArrayList<String> existingPreferenceKey = new ArrayList<>();
```
Comment (mTwTm) [inline app/src/main/java/org/mozilla/focus/telemetry/FirebaseEvent.java]: NIT: consider using HashSet for this operation. HashSet is O(1) search and O(1) insert, while ArrayList is O(n) search and O(n) insert. We don't need duplication and we don't need get for this data.

File: app/src/main/java/org/mozilla/focus/telemetry/FirebaseEvent.java [hunk 3]
```diff
@@ -43,11 +50,23 @@ private FirebaseEvent(@NonNull String category, @NonNull String method, @Nullabl
...
             // TODO: check eventName should start with[a-zA-Z] , contains only [a-zA-A0-9_], and shouldn't
             // TODO: start with ^(?!(firebase_|google_|ga_)).*
-            throw new IllegalArgumentException(this.eventName + " exceeds Firebase event name length limit " + this.eventName.length() + " of " + MAX_LENGTH_EVENT_NAME);
+            final int prefixLength = eventNamePrefix.length();
+
+            if (prefixLength > MAX_LENGTH_EVENT_NAME_PREFIX) {
+                handleError("Event[" + this.eventName + "]'s prefixLength too long  " + prefixLength + " of " + MAX_LENGTH_EVENT_NAME_PREFIX);
+            }
+            if (value != null && isValueInWhiteList(value)) {
+                int acceptValueLength = MAX_LENGTH_EVENT_NAME - eventNamePrefix.length();
```
Comment (mTwTm) [inline app/src/main/java/org/mozilla/focus/telemetry/FirebaseEvent.java]: Maybe we would like to have a test to make sure this is handled correctly? probably through initializing a whitelisted event and check if the length is 40 after the initialization.

File: app/src/main/java/org/mozilla/focus/telemetry/FirebaseEvent.java [hunk 4]
```diff
@@ -23,6 +26,8 @@
     // and "ga_" prefixes are reserved and should not be used.
     // see: https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event
     static final int MAX_LENGTH_EVENT_NAME = 40;
+    // method+object shouldn't longer than 20 characters so value part can have enough space
+    static final int MAX_LENGTH_EVENT_NAME_PREFIX = 20;
```
[the remark this answers is not in the document]
Comment (cnevinc) [reply app/src/main/java/org/mozilla/focus/telemetry/FirebaseEvent.java]: I'll use them in unit test later

File: app/src/main/java/org/mozilla/focus/telemetry/FirebaseEvent.java [hunk 5]
```diff
@@ -43,11 +50,23 @@ private FirebaseEvent(@NonNull String category, @NonNull String method, @Nullabl
...
+
+            if (prefixLength > MAX_LENGTH_EVENT_NAME_PREFIX) {
+                handleError("Event[" + this.eventName + "]'s prefixLength too long  " + prefixLength + " of " + MAX_LENGTH_EVENT_NAME_PREFIX);
+            }
+            if (value != null && isValueInWhiteList(value)) {
+                int acceptValueLength = MAX_LENGTH_EVENT_NAME - eventNamePrefix.length();
+                int valueLength = value.length();
+                this.eventName = eventNamePrefix + value.substring(valueLength - acceptValueLength, valueLength);
+            } else {
+                handleError("Event[" + this.eventName + "] exceeds Firebase event name limit " + this.eventName.length() + " of " + MAX_LENGTH_EVENT_NAME);
```
[the remark this answers is not in the document]
Comment (cnevinc) [reply app/src/main/java/org/mozilla/focus/telemetry/FirebaseEvent.java]: if we reach this line,  means `this.eventName.length() > MAX_LENGTH_EVENT_NAME`
so even if the value is null, it still makes sense to handle the error here.

File: app/src/main/java/org/mozilla/focus/telemetry/FirebaseEvent.java (hunk 3 above)
Comment (cnevinc) [reply app/src/main/java/org/mozilla/focus/telemetry/FirebaseEvent.java]: Do you mean I should create a share preference key <-> firebase event change_setting_pref_key mapping? I think it'll need hardcoded strings and will be hard to maintain. So here I just whitelist existing events and trim them automatically. How do you think?

Comment (mTwTm) [reply app/src/main/java/org/mozilla/focus/telemetry/FirebaseEvent.java]: Oh I didn't make it clear sorry. I mean adding a test.

**Comment by cnevinc** [comment]
Need to write more test before we merge this PR to make sure all method/object/value combination will fit in 40 characters

File: app/src/main/java/org/mozilla/focus/telemetry/FirebaseEvent.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (mTwTm) [reply app/src/main/java/org/mozilla/focus/telemetry/FirebaseEvent.java]: You're right. My bad :P

File: app/src/main/java/org/mozilla/focus/utils/NewFeatureNotice.java [hunk 6]
```diff
@@ -8,7 +8,7 @@
 public class NewFeatureNotice {
 
     private static final String PREF_KEY_BOOLEAN_FIRSTRUN_SHOWN = "firstrun_shown";
-    private static final String PREF_KEY_INT_FEATURE_UPGRADE_VERSION = "firstrun_upgrade_version";
+    public static final String PREF_KEY_INT_FEATURE_UPGRADE_VERSION = "firstrun_upgrade_version";
```
Comment (mTwTm) [inline app/src/main/java/org/mozilla/focus/utils/NewFeatureNotice.java]: Should we add @VisibleForTesting tag?

File: app/src/androidTest/java/org/mozilla/focus/telemetry/TelemetryWrapperTest.java [hunk 7]
```diff
@@ -0,0 +1,579 @@
...
+    public void setUp() {
+        final Context context = InstrumentationRegistry.getInstrumentation().getTargetContext();
+        final String prefName = context.getString(R.string.pref_key_telemetry);
+        final SharedPreferences preferences = PreferenceManager.getDefaultSharedPreferences(context);
+        preferences.edit().putBoolean(prefName, false).apply();
+
+    }
+
+
+    @Test
```
Comment (mTwTm) [inline app/src/androidTest/java/org/mozilla/focus/telemetry/TelemetryWrapperTest.java]: What are the purposes of these three methods?

File: app/src/androidTest/java/org/mozilla/focus/telemetry/TelemetryWrapperTest.java [hunk 8]
```diff
@@ -0,0 +1,579 @@
...
+    public void settingsLearnMoreClickEvent() {
+        activityTestRule.launchActivity(new Intent());
+        Context context = activityTestRule.getActivity();
+        TelemetryWrapper.settingsLearnMoreClickEvent(context.getString(R.string.pref_key_turbo_mode));
+        TelemetryWrapper.settingsLearnMoreClickEvent(context.getString(R.string.pref_key_telemetry));
+
+    }
+
+    @Test
+    public void settingsLocaleChangeEvent() {
```
Comment (mTwTm) [inline app/src/androidTest/java/org/mozilla/focus/telemetry/TelemetryWrapperTest.java]: Why are we commenting out this?

File: app/src/androidTest/java/org/mozilla/focus/telemetry/TelemetryWrapperTest.java (hunk 7 above)
Comment (cnevinc) [reply app/src/androidTest/java/org/mozilla/focus/telemetry/TelemetryWrapperTest.java]: I'll remove unused method later.

File: app/src/androidTest/java/org/mozilla/focus/telemetry/TelemetryWrapperTest.java (hunk 8 above)
Comment (cnevinc) [reply app/src/androidTest/java/org/mozilla/focus/telemetry/TelemetryWrapperTest.java]: I'll add them back

File: app/src/main/java/org/mozilla/focus/utils/NewFeatureNotice.java (hunk 6 above)
Comment (cnevinc) [reply app/src/main/java/org/mozilla/focus/utils/NewFeatureNotice.java]: will do

File: app/src/androidTest/java/org/mozilla/focus/telemetry/TelemetryWrapperTest.java [hunk 9]
```diff
@@ -0,0 +1,571 @@
...
+            TelemetryWrapper.settingsClickEvent(key);
+        }
+    }
+
+    @Test
+    public void settingsLearnMoreClickEvent() {
+        activityTestRule.launchActivity(new Intent());
+        Context context = activityTestRule.getActivity();
+        TelemetryWrapper.settingsLearnMoreClickEvent(context.getString(R.string.pref_key_turbo_mode));
+        TelemetryWrapper.settingsLearnMoreClickEvent(context.getString(R.string.pref_key_telemetry));
```
Comment (cnevinc) [inline app/src/androidTest/java/org/mozilla/focus/telemetry/TelemetryWrapperTest.java]: Instead of calling helper methods directly, I think it makes more sense to test the EventBuilder initialization in the helper methods.

**Comment by cnevinc** [comment]
The build fails due to an intermittent UI test. Not related to this PR. I'll fi it later.
