### PR TITLE
Issues/1831

### LINKED ISSUE #1831: java.lang.IllegalStateException in org.mozilla.focus.activity.MainActivity$3.onQueryComplete
New on 3585

Noticed that it is spanning in various Xiaomi devices while some non-xaomi are suffering too

Ref: https://play.google.com/apps/publish/?account=7083182635971239206#AndroidMetricsErrorsPlace:p=org.mozilla.rocket&appVersion=CANARY&clusterName=apps/org.mozilla.rocket/clusters/8e4751ec&detailsSpan=7

java.lang.IllegalStateException: 
 
  at org.mozilla.focus.activity.MainActivity$3.onQueryComplete (MainActivity.java:852)
 
  at org.mozilla.focus.download.DownloadInfoManager$DownloadInfoQueryHandler.onQueryComplete (DownloadInfoManager.java:117)
 
  at android.content.AsyncQueryHandler.handleMessage (AsyncQueryHandler.java:344)
 
  at android.os.Handler.dispatchMessage (Handler.java:102)
 
  at android.os.Looper.loop (Looper.java:148)
 
  at android.app.ActivityThread.main (ActivityThread.java:5480)
 
  at java.lang.reflect.Method.invoke (Native Method)
 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:728)
 
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:618)

### PR DESCRIPTION
**Pull request by mTwTm**
Fixes #1831 (Hopefully, we're uncertain of the STR)

### CODE REVIEW

File: app/src/main/java/org/mozilla/focus/components/RelocateService.java [hunk 1]
```diff
@@ -125,6 +125,11 @@ private void handleActionMove(final long rowId,
                                   final long downloadId,
                                   @NonNull final File srcFile,
                                   @Nullable final String mediaType) {
+        // if the download id is not in our database, ignore this operation
+        final DownloadInfoManager mgr = DownloadInfoManager.getInstance();
+        if (!mgr.recordExists(downloadId)) {
```
Comment (mxlius) [inline app/src/main/java/org/mozilla/focus/components/RelocateService.java]: If return here does not do anything(such as broadcastRelocateFinished), would it be better if we move this check out to its callee?
